version: '3.5'
services:
    postgres:
        image: postgres:latest
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./docker/postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

networks:
  default:
    name: scraper
    driver: bridge
